name = "Vanillish"
author = "Ryan Cao"
version = "2.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "038412821dbb16c38533684693a5692e980566223a44a2139ec9bca18165f468"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.14"

[options]
acceptable-game-versions = []
