name = "Vanillish"
author = "Ryan Cao"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66650c0d62d86a4adfa8cc5a8b007bdc80cdd03cc86c7a951a292fc40698cda4"

[versions]
minecraft = "1.20.1"
quilt = "0.19.3-beta.1"

[options]
acceptable-game-versions = ["1.20"]
