name = "Vanillish"
author = "Ryan Cao"
version = "1.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3042eae7dc2d0ef962f87713af1e87009fd3d2824d77997c32eb1d600f5574c"

[versions]
fabric = "0.14.10"
minecraft = "1.19.3"
